apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "guacamole-db"
  labels:
    app: guacamole-db
spec:
  replicas: 1
  selector:
    name: guacamole-db
  strategy:
    resources: {}
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: guacamole-db
    spec:
      volumes:
        - name: container-scripts
          persistentVolumeClaim:
            claimName: container-scripts
        - emptyDir: {}
          name: guacamole-db-data
      containers:
      - env:
        - name: GUACD_HOSTNAME
          value: guacamole-server
        - name: GUACD_PORT
          value: 4822
        - name: MYSQL_PASSWORD
          value: some_password
        - name: MYSQL_DATABASE
          value: guacamole_db
        - name: MYSQL_USER
          value: guacamole_user
        - name: MYSQL_HOSTNAME
          value: guacamole-db
        - name: MYSQL_PORT
          value: 3306
        image: jboss-webserver30-tomcat8-openshift:latest
        imagePullPolicy: IfNotPresent
        name: guacamole-client:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: container-scripts
          mountPath: /usr/share/container-scripts/mysql/
        - name: guacamole-db-data
          mountPath: /var/lib/mysql/data
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - guacamole-db
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: jboss-webserver30-tomcat8-openshift:latest
    type: ImageChange
